# Generated by Django 5.1.2 on 2024-10-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='images/defaultimage.jpeg', upload_to='images'),
        ),
    ]
