# Generated by Django 5.1.2 on 2024-11-03 14:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
