# Generated by Django 5.1.2 on 2024-11-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0013_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
